spring:
  datasource:
    url: jdbc:mysql://splitease.cp26igqka5t4.eu-north-1.rds.amazonaws.com:3306?createDatabaseIfNotExist=true
    username: vasu0402
    password: vasu0402
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update