spring:
  datasource:
    url: jdbc:mysql://root:ghFPFZGLtoqbjBiquiXkgCqHMaHTKzVU@autorack.proxy.rlwy.net:36868/railway
    username: root
    password: ghFPFZGLtoqbjBiquiXkgCqHMaHTKzVU
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update