server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://splitease.cz4ec6qygva3.us-east-1.rds.amazonaws.com:3306/splitease?createDatabaseIfNotExist=true
    username: vasu0402
    password: {SPLITEASE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

logging:
  level:
    #    root: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
        com:
          vr:
            SplitEase: DEBUG