server:
  port: 9090

spring:
#  profiles:
#    active: dev
  application:
    name: "SplitEase"

  #    EMAIL CONFIGURATION
  mail:
    host: smtp.gmail.com
    port: 587
    username: split.ease01@gmail.com
    password: knodvyhzpqgihrpn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #    File Configuration
#  servlet:
#    multipart:
#      max-file-size: 3MB
#      max-request-size: 3MB

  jpa:
#    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/splitease?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE

# swagger-ui custom path
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html